DEBUG 2020-05-12 06:36:37.594 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-12 06:36:37.605 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-12 06:36:37.606 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-12 06:36:37.606 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
INFO 2020-05-12 06:36:37.607 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH4_RunA_cfg.py
DEBUG 2020-05-12 06:36:37.607 UTC: 	 Loading CRAB configuration file.
ERROR 2020-05-12 06:36:37.610 UTC: 	 Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-05-12 06:36:37.610 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-05-12 10:40:34.585 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-12 10:40:34.602 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-12 10:40:34.603 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-12 10:40:34.603 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
INFO 2020-05-12 10:40:34.604 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH4_RunA_cfg.py
DEBUG 2020-05-12 10:40:34.604 UTC: 	 Loading CRAB configuration file.
ERROR 2020-05-12 10:40:34.608 UTC: 	 Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-05-12 10:40:34.608 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-05-13 18:50:42.812 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-13 18:50:42.813 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-13 18:50:42.826 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-13 18:50:42.826 UTC: 	 Executing command: 'status'
DEBUG 2020-05-13 18:50:42.826 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2020-05-13 18:50:42.828 UTC: 	 Error: crab_SkimTau3Mu_BParking_Run2018C_BPH3_Mini_v5 is not a valid CRAB project directory.
ERROR 2020-05-13 18:50:42.828 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_SkimTau3Mu_BParking_Run2018C_BPH3_Mini_v5 is not a valid CRAB project directory.
INFO 2020-05-13 18:50:42.854 UTC: 	 Log file is /lustrehome/venditti/Tau3Mu_MiniAOD/CMSSW_10_2_1/src/CrabSubmission/Data/BParking_RunC_Mini/crab.log
DEBUG 2020-05-13 18:50:47.438 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-13 18:50:47.439 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-13 18:50:47.455 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-13 18:50:47.455 UTC: 	 Executing command: 'status'
DEBUG 2020-05-13 18:50:47.456 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2020-05-13 18:50:47.457 UTC: 	 Error: crab_SkimTau3Mu_BParking_Run2018C_BPH3_Mini_v5 is not a valid CRAB project directory.
ERROR 2020-05-13 18:50:47.457 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_SkimTau3Mu_BParking_Run2018C_BPH3_Mini_v5 is not a valid CRAB project directory.
INFO 2020-05-13 18:50:47.460 UTC: 	 Log file is /lustrehome/venditti/Tau3Mu_MiniAOD/CMSSW_10_2_1/src/CrabSubmission/Data/BParking_RunC_Mini/crab.log
